# Generated by Django 4.2.5 on 2023-10-13 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("productmanagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(default=None, max_length=200)),
                ("lastname", models.CharField(default=None, max_length=200)),
                ("state", models.CharField(default=None, max_length=200)),
                ("address", models.CharField(default=None, max_length=500)),
                ("city", models.CharField(default=None, max_length=100)),
                ("postcode", models.CharField(max_length=20)),
                ("phoneno", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Myorders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("amount", models.CharField(max_length=10, null=True)),
                ("method", models.CharField(max_length=100, null=True)),
                ("productname", models.CharField(max_length=100, null=True)),
                ("image", models.ImageField(upload_to="order_images")),
                ("status", models.BooleanField(default=True)),
                ("totalamount", models.IntegerField()),
                ("orderid", models.CharField(default="1", max_length=150)),
                ("orderdate", models.DateTimeField(auto_now_add=True, null=True)),
                ("orderstatus", models.CharField(default="Placed", max_length=50)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ordermanagement.address",
                    ),
                ),
                (
                    "productid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productmanagement.stock",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
