# Generated by Django 4.2.5 on 2023-10-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gameadmin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("quantity", models.CharField(max_length=10)),
                ("stock", models.IntegerField()),
                ("description", models.CharField(max_length=600)),
                ("image1", models.ImageField(upload_to="stock_images")),
                ("image2", models.ImageField(upload_to="stock_images")),
                ("image3", models.ImageField(upload_to="stock_images")),
                ("image4", models.ImageField(upload_to="stock_images")),
                ("proOffer", models.IntegerField(default=5)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gameadmin.categories",
                    ),
                ),
            ],
        ),
    ]
