# Generated by Django 4.2.5 on 2023-10-13 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("productmanagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productname", models.CharField(max_length=200)),
                ("price", models.IntegerField(null=True)),
                ("image", models.ImageField(upload_to="wishlist_images")),
                ("description", models.CharField()),
                (
                    "productid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productmanagement.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guestcart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userreference", models.CharField(max_length=200, null=True)),
                ("productname", models.CharField(max_length=200)),
                ("price", models.IntegerField(null=True)),
                ("image", models.ImageField(upload_to="pics")),
                ("quantity", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "productid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productmanagement.stock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productname", models.CharField()),
                ("price", models.IntegerField(null=True)),
                ("image", models.ImageField(upload_to="Cart_images")),
                ("quantity", models.IntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "productid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="productmanagement.stock",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
